### ISSUE TITLE
Crash in your example projcect

### ISSUE THREAD

**Issue by yormy** [tony-xlh/vision-camera-dynamsoft-document-normalizer#3]
When  compile and your your exmple project on my device it crashes when loading the cropper

`
 LOG  steady
 LOG  back to cropper
 LOG  is focused
 LOG  update pointsData
 LOG  
 LOG  pointsText changed
 LOG  previousResults
 LOG  {"current": []}
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: Attempt to get length of null array
Error: Attempt to get length of null array

`

**Comment by tony-xlh** [comment]
What device are you using?

**Comment by AleksandrTermenzhy** [comment]
Not sure if it's the same but I'm seeing a lot of errors for Android when running DDN (Android 13, Pixel 6):
```
java.lang.NullPointerException: Attempt to get length of null array
    at com.visioncameradynamsoftdocumentnormalizer.VisionCameraDetectionPlugin.callback(VisionCameraDetectionPlugin.java:19)
```

It doesn't seem to cause any issues with detection per se, but perhaps it would make sense to handle this case with something like :
```java
        DetectedQuadResult[] quadResults = mModule.detectImageProxy(image);

        if (quadResults != null) { // <-- add this check
             for (DetectedQuadResult quad : quadResults) {
                 // ...
             }
        }
```

**Comment by xulihang** [comment]
I use try catch for this exception so it does not crash. I've added the null checking: https://github.com/tony-xlh/vision-camera-dynamsoft-document-normalizer/commit/2a6f428e0dc8a1be3c4e5d5610946f0952be6ce5
