### ISSUE TITLE
Vision camera v3 support

### ISSUE THREAD

**Issue by AleksandrTermenzhy** [tony-xlh/vision-camera-dynamsoft-document-normalizer#4]
Hello!

I was wondering if there are any plans to migrate to `react-native-vision-camera@3.x.x` since it appears that version 2 is losing support from the vision camera maintainer.

Could you also describe some high-level issues that need to be addressed for this support to be implemented?

Thank you in advance!

**Comment by xulihang** [comment]
Hi there,

I will try to upgrade the barcode plugin first. You can find the related issue here: https://github.com/tony-xlh/vision-camera-dynamsoft-barcode-reader/issues/15

**Comment by xulihang** [comment]
I've released a 1.0.0 version which is for vision camera v3.
