### ISSUE TITLE
android getOrientation() in Frame.java no longer returns UnionValue in vision camera 3.7+

### ISSUE THREAD

**Issue by frenberg** [tony-xlh/vision-camera-dynamsoft-document-normalizer#5]
Hey,

just an FYI that the library does not compile on android with latest vision camera version 3.7.0 since it was a breaking change introduced in Frame.java.

https://github.com/tony-xlh/vision-camera-dynamsoft-document-normalizer/blob/main/android/src/main/java/com/visioncameradynamsoftdocumentnormalizer/BitmapUtils.java#L78C51-L78C51

https://github.com/mrousavy/react-native-vision-camera/blob/v3.7.0/package/android/src/main/java/com/mrousavy/camera/frameprocessor/Frame.java#L86

**Comment by xulihang** [comment]
Thanks for the notice. I will try to keep the library up with the latest version of vision camera.

**Comment by xulihang** [comment]
2.1.0 now supports vision-camera 3.8.
