### ISSUE TITLE
NormalizeFile gives "Error: length=0; index=0" if quadrilateral has point outside of image edges

### ISSUE THREAD

**Issue by frenbergFNX** [tony-xlh/vision-camera-dynamsoft-document-normalizer#7]
We've had an issue with what I believe to be the code [here in normalizeFile](https://github.com/tony-xlh/vision-camera-dynamsoft-document-normalizer/blob/main/android/src/main/java/com/visioncameradynamsoftdocumentnormalizer/VisionCameraDynamsoftDocumentNormalizerModule.java#L175) at line 175 which will throw an array index out of bounds error.
This seems to happen if we forexample have an image with dimensions 960x2080 and pass a quadrilatera with one point beeing located on the edge of the image ie at y value = 2080. 
We can sanitize the input so its not a big deal but would be nice to have a proper return code for this. I think maybe we got "invalid quadrilateral" before we upgraded.

**Comment by xulihang** [comment]
Since it directly normalizes a file based on its path, I don't know its width and height so that I can make sure it is because of this problem. Is it necessary to return the "invalid quadrilateral" message? Does the current error message not suffice?

**Comment by frenbergFNX** [comment]
It feels weird that we need code like this: "return valY >= photoHeight ? photoHeight - 1 : valY;" in onTouchMove (Notice the return of **photopHeight - 1**) but you are right, the error message doesn't matter so you can close this issue :)
